import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const  RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Toaster position='top-center' reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}

export default RootLayout