import Header from "@/components/dashboard/Header";

export const metadata = {
  title: 'Inventory Dashboard',
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <div className={'flex'}>
      <aside className='w-56 min-h-screen bg-sky-900 text-slate-50'>Sidebar</aside>
      <main className="w-full bg-slate-100 min-h-screen">
        <Header />
        {children}</main>
    </div>
  );
}
