import Header from '@/components/dashboard/Header';
import Sidebar from '@/components/dashboard/Sidebar';

export const metadata = {
  title: 'Inventory Dashboard',
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <div className={'flex'}>
      <Sidebar />
      <Header />
      <main className='w-full bg-slate-100 min-h-screen pt-[100px] pl-60'>{children}</main>
    </div>
  );
}
